"""added a column for solutin_description

Revision ID: 993bcfb419f3
Revises: e08a6d8fecff
Create Date: 2025-03-02 10:56:47.714777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '993bcfb419f3'
down_revision = 'e08a6d8fecff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('solution_description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_column('solution_description')

    # ### end Alembic commands ###
