"""Add profile picture field with default value to User model

Revision ID: 993b5342d787
Revises: ed3b3d48bdec
Create Date: 2025-03-03 11:16:15.482919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '993b5342d787'
down_revision = 'ed3b3d48bdec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_picture')

    # ### end Alembic commands ###
