"""added created at in the solution and problem model

Revision ID: ecf9b66ea17a
Revises: f35b2fee0d91
Create Date: 2025-02-26 14:10:09.607423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecf9b66ea17a'
down_revision = 'f35b2fee0d91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problems', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('solutions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))

    with op.batch_alter_table('solutions', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('problems', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
